name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and dependencies based on the package-lock.jason file

inputs:
  node-version:
    description: NodeJS version to use
    default: 22.x
    required: true
  working-dir:
    description: The working directory of the application
    default: .
    required: false

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-dir }}


