name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-versions: '20.x'
        - name: Install Dependencies
          run: npm install

    # 1. Checkout code
    # 2. Install deps of our react application
    # 3. Executes automated tests