name: 06 - Contexts
run-name: 06 -Contexts | DEBUG - ${{ inputs.debug }}
on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

env:
    MY_WORKFLOW_VAR: "workflow"
    MY_OVERWRITTEN_VAR: "workflow"


jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: 'job'
            MY_OVERWRITTEN: 'job'
        steps:
            - name: Display Informantion
              run: |
                echo "Event Name:${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"
            - name: Retrive Variable
              run: |
                echo "Variable value: ${{ vars.MYVAR }}"
            - name: Print Env Variable
              env:
                MY_OVERWRITTEN: 'step'
              run: |
                echo "workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: Print Env Variable
              env:
                MY_OVERWRITTEN: 'step'
              run: |
                echo "workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
