name: 17 - 1 - Custom Actions - Composite

on: 
    workflow_dispatch:

env: 
    working-directory: 17-custom-actions/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-ditectory }}
        steps:
            - uses: actions/checkout@v4
            - name: Step Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                node-version: 22.x
                workinf-dir: ${{ env.working-directory }} 
            - name: Test
              run: npm run test
            - name: Build
              run: npm run build